[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "offline_assistant-llmbridge"
version = "0.1.0"
description = "Modular LLM connector for offline assistant"
